---
galaxy_info:
  author: Berry Langerak
  description: A role for installing and configuring PHP.
  company: Enrise
  license: BSD
  min_ansible_version: 1.5

  platforms:
  - name: Ubuntu
    versions:
    - trusty

categories:
  - development
  - web

dependencies: []

